# Generated by Django 4.2.7 on 2023-11-24 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TodoListApp', '0002_customuser'),
        ('TodoListApp', '0002_todo_user'),
    ]

    operations = [
    ]
