# Generated by Django 4.2.7 on 2023-11-24 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TodoListApp', '0003_merge_0002_customuser_0002_todo_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
